export const ActionTypes = {
    TOGGLE_THEME: 'TOGGLE_THEME',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_CHANGE:'LOGIN_CHANGE',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS'
}